tasks
js-tasks-ru/js-20200622_yurj9999 pull request #7
Opened 2020-07-11 18:26 UTC by yurj9999

2020-07-11 18:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be shown when moving over the element with data-tooltip attribute
+ should have ability to be destroyed
- should be rendered correctly
- should be hidden when moving out from the element with data-tooltip attribute
```

2020-07-12 07:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
- should be rendered correctly
- should have ability to set slider boundaries
- should have ability to set selected range
- should have ability to move left slider to start boundary
- should have ability to move right slider to end boundary
- should have ability to select all range
- should have ability to select single value (when min and max range equal)
- should have ability to set range value, for example: usd, eur, etc.
- should produce event "range-select"
- should have a new ranges in produced event
- should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2020-07-12 12:46 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +  sortingOptions = {
эти значения было бы неплохо получать динамически в конструкторе

2020-07-12 12:47 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +  constructor(header = [], {
вот здесь:
```
  constructor(headersConfig, {
    data = [],
    sorted = {
      id: headersConfig.find(item => item.sortable).id,
      order: 'asc'
    }
  } = {}) {
```

2020-07-12 12:49 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements['header'].addEventListener('pointerdown', this._sorting.bind(this));
если свойство объекта к которому Вы хотите обратиться не вычисляется, а в данном случае это просто строка 'header', то нет абсолютно никакой необходимости обращаться к этому свойству через квадратные скобки - используйте обращение через точку
```
this.subElements.header.addEventListener
```

2020-07-12 12:50 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    const isSortable = target.dataset.hasOwnProperty('sortable');
здесь нет необходимости в проверке `hasOwnProperty`

2020-07-12 12:51 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        target.dataset.order === '' || target.dataset.order === 'asc' ? 'desc' : 'asc');
не используйте условные конструкции в качестве аргументов методов

2020-07-12 12:53 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      sortData.sort((first, second) => this._sortIt(first, second, field));
метод `_sortIt` используется только внутри метода `sort` - Вы уверены что необходимо эту логику выносить за переделы метода `sort`?

2020-07-12 12:55 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements['header'].innerHTML = this._head(headerData);
1. используйте деструкцию
2. не следует в данном случае обращаться через квадратные скобки к свойствам объекта.

```
const { header, body } = this.subElements;

header.innerHTML = this._head(headerData);
body.innderHTML  = this._body(bodyData);
```

2020-07-12 12:55 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements['header'].removeEventListener('pointerdown', this._sorting);
снова квадратные скобки!

2020-07-12 12:55 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.hasOwnProperty('tooltip')) {
Зачем используете `hasOwnProperty`?

2020-07-12 12:58 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.hasOwnProperty('tooltip')) {
зачем используете `hasOwnProperty`?

2020-07-12 13:01 UTC, dosandk requested changes
Посмотрите и исправьте пожалуйста комментарии.
3 вопроса на которые нужно ответить:
* почему имена большинства методов начинаются с нижнего подчеркивания "_"?
* зачем используете метод `hasOwnProperty` - смотрите коммент?
* почему к свойствам объекта обращаетесь через квадратные скобки: `this.subElements['header']`?

2020-07-13 14:33 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements['header'].addEventListener('pointerdown', this._sorting.bind(this));
поправил

2020-07-13 14:47 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +    const isSortable = target.dataset.hasOwnProperty('sortable');
поправил

2020-07-13 14:51 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +        target.dataset.order === '' || target.dataset.order === 'asc' ? 'desc' : 'asc');
поправил

2020-07-13 14:53 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +      sortData.sort((first, second) => this._sortIt(first, second, field));
поправил

2020-07-13 15:22 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements['header'].innerHTML = this._head(headerData);
Не уверен из-за чего, но так сортировка не работает, может это из-за того, что при деструктуризации в header и body записываются копии элементов ?

2020-07-13 15:24 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements['header'].removeEventListener('pointerdown', this._sorting);
поправил

2020-07-13 15:28 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +  sortingOptions = {
поправил

2020-07-13 15:28 UTC, yurj9999 commented on 06-events-practice/1-sortable-table-v2/index.js
> +  constructor(header = [], {
ок, поправил

2020-07-13 15:33 UTC, yurj9999 commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.hasOwnProperty('tooltip')) {
поправил

2020-07-13 15:34 UTC, yurj9999 commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.hasOwnProperty('tooltip')) {
поправил, использовал, потому, что все проверял на true\false, но и впрямь нет в этом смысла, т.к. if преобразует в boolean сам

2020-07-13 16:05 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-15 10:02 UTC, dosandk approved these changes
good 👍

2020-07-15 10:02 UTC, merged